name:  Build

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: install dependencies
        run:  yarn ci
      - name: run build-css
        run: yarn build-css
      - name: run linter
        run: yarn eslint
#      - name: test
#        run: yarn test
  build:
    ## Send sourcemap to sentry

    # Should uncomment this
    # if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name : Release
        run: SENTRY_AUTH_TOKEN=${{secrets.SENTRY_AUTH_TOKEN}} SENTRY_PROJECT=react SENTRY_ORG=${{ secrets.SENTRY_ORG}} yarn release
