name:  TEST

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: remove node_modules
        run:  yarn preci
      - name: install dependencies
        run:  yarn ci
      - name: run linter
        run: yarn eslint
      - name: test
        run: yarn test
